DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID INT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS WRITERS;
CREATE TABLE WRITERS(ID INT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID INT PRIMARY KEY, NAME VARCHAR(255));



DROP TABLE IF EXISTS BOOK_GENRE;

CREATE TABLE  BOOK_GENRE (
ID INT PRIMARY KEY,

BOOKID int,
FOREIGN KEY (BOOKID) REFERENCES BOOKS(ID),

GENREID int,
FOREIGN KEY (GENREID) REFERENCES GENRES(ID)

)


;
DROP TABLE IF EXISTS BOOK_AUTHOR;
CREATE TABLE  BOOK_AUTHOR (
ID INT PRIMARY KEY,

BOOKID int,
FOREIGN KEY (BOOKID) REFERENCES BOOKS(ID),

AUTHORID int,
FOREIGN KEY (AUTHORID) REFERENCES WRITERS(ID)

)

