DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID INT PRIMARY KEY AUTO_INCREMENT, title VARCHAR(255));

DROP TABLE IF EXISTS WRITERS;
CREATE TABLE WRITERS(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255));



DROP TABLE IF EXISTS BOOK_GENRE;

CREATE TABLE  BOOK_GENRE (
ID INT PRIMARY KEY AUTO_INCREMENT,

BOOKID int,
FOREIGN KEY (BOOKID) REFERENCES BOOKS(ID)  ON UPDATE CASCADE ON DELETE CASCADE ,

GENREID int,
FOREIGN KEY (GENREID) REFERENCES GENRES(ID) ON UPDATE CASCADE ON DELETE CASCADE

)


;
DROP TABLE IF EXISTS BOOK_AUTHOR;
CREATE TABLE  BOOK_AUTHOR (
ID INT PRIMARY KEY AUTO_INCREMENT,

BOOKID int,
FOREIGN KEY (BOOKID) REFERENCES BOOKS(ID) ON UPDATE CASCADE ON DELETE CASCADE ,

AUTHORID int,
FOREIGN KEY (AUTHORID) REFERENCES WRITERS(ID) ON UPDATE CASCADE ON DELETE CASCADE

)

